[package]
name = "audio-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
mdns-sd = "0.5"
tokio = { version = "1", features = [ "macros", "rt", "sync" ] }
#tungstenite = "0.18.0"
#serde = { version = "1.0.152", features = [ "derive" ] }
