[package]
name = "audio-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
mdns-sd = "0.5"
tungstenite = "0.18"
local-ip-address = "0.5"
#serde = { version = "1.0.152", features = [ "derive" ] }
